services:
  web:
    command: npm run dev -- --hostname 0.0.0.0
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - ../apps/web/app:/app/app
      - ../apps/web/public:/app/public
      - ../apps/web/next.config.mjs:/app/next.config.mjs
      - ../apps/web/next-env.d.ts:/app/next-env.d.ts
      - ../apps/web/tsconfig.json:/app/tsconfig.json
      - ../apps/web/package.json:/app/package.json
